language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

script: ./gradlew check

notifications:
  email: false
  slack:
    rooms:
      secure: aPtQwxPRb8LnUwoP6i+EL5rhTtmwkqPR68gQy/bAgnW8bV4/9yFmnyKc/U3VkvD/oIB1xCcbSkuL2An40tktQhllh7xykG/5dNbxqqxydrFbzEjFewBdIzEg+KZnXBdQE91edltA/QoWGEIZmVv3hU/AS7/uo0d5SStdF5VhSIZ9rawbE2hnT2ca3TN90ZI0/q33o7wDQwgzP0AnEtvxVjmVGJxPgD4uPXpr1wS3yi2MBKRNMi9GWRbyQGgRX9HyCrx6S37Dt/cHengbHoN8ZXYOfZylKAxcFXFjoqaBvQyZBjDQ8/LJn6FCry44mwzd1Bzl7xc6wz92ag1KdMX6pdx3m3HcHyl06EC8AZDIJ+0lYqvsBcUjJoJq8wc6D9jDzvWAOgiQuiw47f5BHycB/LZcuDPPTvIVrEamQiMtBJrqHirOaadzGJOVaadbMvaaGbqk2BOmnauq+KeAYJBpG9Ed6MjJQ5K6efNiw9grIW7R36GZomykpc7N/5GpWVveaBBYW6WIMfhLrdehztOWIhO4qTxJveE55CjQy0GbIbxb25nIsq7agY2CutxdZLmInYp+d+ERlFlmjXd4O5PSeVAzLHoji/XnG28HLQJ0g3P7GRZ6RzY47OUOKS2WG4q76BKUBniLfZ6jr3idwKAp/Xf9PM2ylavPVwsopdlWHh0=
    on_success: change
